Add trigger to performance tests daily
elastic/kibana-buildkite pull request #6
Opened 2021-11-29 17:21 UTC by suchcodemuchwow

2021-11-29 17:53 UTC, brianseeders approved these changes

2022-01-18 11:51 UTC, suchcodemuchwow commented on pipelines/kibana-performance-daily.tf
> +  name        = "kibana / performance daily"
I renamed the "nightly->daily" everywhere to be consistent, is it ok ? @spalger

2022-03-09 15:04 UTC, spalger commented on pipelines/kibana-performance-daily.tf
> +  name        = "kibana / performance daily"
Old comment, but should be fine, just make sure you check the changes this is going to do by running `terraform plan` locally.

2022-03-09 16:06 UTC, brianseeders requested changes

2022-03-09 16:06 UTC, brianseeders commented on pipelines/kibana-performance-daily.tf
> +    TEST_BROWSER_HEADLESS=1
You shouldn't need this, as it gets set everywhere in CI here: https://github.com/elastic/kibana/blob/main/.buildkite/scripts/common/env.sh#L36

2022-03-09 21:57 UTC, brianseeders approved these changes

2022-03-09 22:20 UTC, merged